export const demoPosts = [
  {
    postId: '11001',
    userId: 'user005',
    userName: 'Taliyah Ruiz',
    userAvatar: '/img/g4.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'One_Day',
      audioTitle: 'One Day',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '11002',
    userId: 'user006',
    userName: 'Kelsea Stevenson',
    userAvatar: '/img/g5.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'Before_You_Break_My_Heart',
      audioTitle: 'Before You Break My Heart',
      audioImage: 'album_Me_And_Jerry_Reed',
      album: 'Me And Jerry Reed',
      artist: 'BETP5',
      audioType: '',
    },
    isLiked: 1,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '11003',
    userId: 'user007',
    userName: 'Ashley Mill',
    userAvatar: '/img/g6.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'No_Country_Song',
      audioTitle: 'No Country Song',
      audioImage: 'album_High_Tonight',
      album: 'High Tonight',
      artist: 'THEJUNETOMINFLUENCE',
      audioType: 'Rock',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '11004',
    userId: 'user004',
    userName: 'Viki Viki',
    userAvatar: '/img/g3.jpg',
    postType: 'event',
    contentObj: {
      contentId: '66253',
      contentTitle: "Jerry's OMG concert",
      contentPhoto: 'e1',
      contentURL: 'string',
      contentType: 'event',
      audioId: '132456gh',
      audioSrc: 'Old_Russian_Waltz_2-Romantic_Piano_Music',
      audioTitle: 'Romantic Piano Music',
      audioImage: 'album_Old_Russian_Waltz',
      album: 'Old Russian Waltz 2',
      artist: 'THE PIANO LADY (LENA ORSA)',
      audioType: 'Piano',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '11005',
    userId: 'user009',
    userName: 'Andrew Almond',
    userAvatar: '/img/b1.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'The_corn_road',
      audioTitle: 'The corn road',
      audioImage: 'album_The_corn_road',
      album: 'The corn road',
      artist: 'FLASHINMUSIC',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '11006',
    userId: 'user010',
    userName: 'Alton Roberts',
    userAvatar: '/img/b2.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: '132456gh',
      audioSrc: 'Old_Russian_Waltz_2-Romantic_Piano_Music',
      audioTitle: 'Romantic Piano Music',
      audioImage: 'album_Old_Russian_Waltz',
      album: 'Old Russian Waltz 2',
      artist: 'THE PIANO LADY (LENA ORSA)',
      audioType: 'Piano',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  
];

export const hiddenDemoPost = [
  {
    postId: '12007',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: 'audio008',
      audioSrc: 'One_Day',
      audioTitle: 'One Day',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12008',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: 'audio001',
      audioSrc: 'I_Hope_She_s_Not_Cold',
      audioTitle: 'I Hope She is Not Cold',
      audioImage: 'album_american_country',
      album: 'American Country',
      artist: 'Andy_Blackwood',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },

  {
    postId: '12009',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'event',
    contentObj: {
      contentId: '66253',
      contentTitle: 'A Fantastic Concert',
      contentPhoto: 'e3',
      contentURL: 'string',
      contentType: 'event',
      audioId: 'audio002',
      audioSrc: 'I_dance_to_the_Jazz_of_the_50s',
      audioTitle: 'I dance to the Jazz of the 50s',
      audioImage: 'album_I_dance_to_the_Jazz_of_the_50s',
      album: 'I dance to the Jazz of the 50s',
      artist: 'AURBANNIAUDIO',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12010',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: 'audio003',
      audioSrc: 'Me_And_Jerry_Reed',
      audioTitle: 'Me And Jerry Reed',
      audioImage: 'album_Me_And_Jerry_Reed',
      album: 'Me And Jerry Reed',
      artist: 'BETP5',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12011',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: 'audio004',
      audioSrc: 'Before_You_Break_My_Heart',
      audioTitle: 'Before You Break My Heart',
      audioImage: 'album_Me_And_Jerry_Reed',
      album: 'Me And Jerry Reed',
      artist: 'BETP5',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12012',
    userId: 'user001',
    userName: 'Mike Chen',
    userAvatar: '/img/me.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: 'audio017',
      audioSrc: 'Summer',
      audioTitle: 'Summer',
      audioImage: 'album_Show_it_to_your_Mother',
      album: 'Show it to your Mother',
      artist: 'RUSTY TEA MAKERS',
      audioType: 'Rock',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12013',
    userId: 'user008',
    userName: 'Shelly Mooney',
    userAvatar: '/img/g7.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: 'audio014',
      audioSrc: 'How_We_Got_Here',
      audioTitle: 'How We Got Here',
      audioImage: 'album_How_We_Got_Here',
      album: 'How We Got Here',
      artist: 'EXPLOSIVE EAR CANDY',
      audioType: 'Rock',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12014',
    userId: 'user012',
    userName: 'Payton Sellers',
    userAvatar: '/img/b4.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: 'audio015',
      audioSrc: 'Safe_and_Warm_in_Hunter_s_Arms',
      audioTitle: "Safe and Warm in Hunter's Arms",
      audioImage: 'album_Little_Liar_Single',
      album: 'Little Liar Single',
      artist: 'ROLLER GENOA',
      audioType: 'Rock',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12014',
    userId: 'user011',
    userName: 'Danyal Myers',
    userAvatar: '/img/b3.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: 'audio016',
      audioSrc: 'Monkeys_Jumping',
      audioTitle: 'Monkeys Jumping',
      audioImage: 'album_Show_it_to_your_Mother',
      album: 'Show it to your Mother',
      artist: 'RUSTY TEA MAKERS',
      audioType: 'Rock',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
  {
    postId: '12015',
    userId: 'user002',
    userName: 'Trang Lê',
    userAvatar: '/img/g1.jpg',
    postType: 'album',
    contentObj: {
      contentId: 'string',
      contentTitle: '',
      contentPhoto: 'string',
      contentURL: 'string',
      contentType: 'album',
      audioId: 'audio009',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
    isLiked: 0,
    comments: [],
    loading: false,
    error: '',
  },
]