
export const demoProfiles = [
  {
  userId: 'user001',
  userName: 'Mike Chen',
  userAvatar: '/img/me.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Mike Chen, I am a photographer and software developer in Taipei.',
  userCompany: 'Nuts Tech',
  userJobTitle: 'Frontend Developer',
  userEducation: 'National Yang Ming Chiao Tung University',
  userLocation: 'Taipei',
  userInstagram: 'magicmike.taipei',
  userRelationship: 'In relationship with Marisa Klodklaw',
  userFavAlbums: [
    {
      audioId: 'audio008',
      audioSrc: 'One_Day',
      audioTitle: 'One Day',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
    {
      audioId: 'audio010',
      audioSrc: 'French_Kisses_And_Cat_Hair',
      audioTitle: 'French Kisses And Cat Hair',
      audioImage: 'album_Very_Good_Album',
      album: 'Very Good Album',
      artist: 'Michael Ellis',
      audioType: '',
    },
    {
      audioId: 'audio012',
      audioSrc: 'No_Country_Song',
      audioTitle: 'No Country Song',
      audioImage: 'album_High_Tonight',
      album: 'High Tonight',
      artist: 'THEJUNETOMINFLUENCE',
      audioType: 'Rock',
    },
    {
      audioId: 'audio014',
      audioSrc: 'How_We_Got_Here',
      audioTitle: 'How We Got Here',
      audioImage: 'album_How_We_Got_Here',
      album: 'How We Got Here',
      artist: 'EXPLOSIVE EAR CANDY',
      audioType: 'Rock',
    },
    {
      audioId: 'audio016',
      audioSrc: 'Monkeys_Jumping',
      audioTitle: 'Monkeys Jumping',
      audioImage: 'album_Show_it_to_your_Mother',
      album: 'Show it to your Mother',
      artist: 'RUSTY TEA MAKERS',
      audioType: 'Rock',
    },
    {
      audioId: 'audio018',
      audioSrc: 'Mourning_Day',
      audioTitle: 'Mourning Day',
      audioImage: 'album_Mourning_Day',
      album: 'Mourning Day',
      artist: 'SADME',
      audioType: 'Rock',
    },
    {
      audioId: 'audio019',
      audioSrc: 'Graveyard',
      audioTitle: 'Graveyard',
      audioImage: 'album_2_Days_A_Night',
      album: '2 Days A Night',
      artist: 'THE LIQUID KITCHEN',
      audioType: 'Rock',
    },
  ],
},
{
  userId: 'user002',
  userName: 'Trang Lê',
  userAvatar: '/img/g1.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Trang Lê',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},
{
  userId: 'user003',
  userName: 'Victoria Wirya',
  userAvatar: '/img/g2.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Victoria Wirya',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},
{
  userId: 'user004',
  userName: 'Viki Viki',
  userAvatar: '/img/g3.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Viki Viki',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},
{
  userId: 'user005',
  userName: 'Taliyah Ruiz',
  userAvatar: '/img/g4.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Taliyah Ruiz',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},
{
  userId: 'user006',
  userName: 'Kelsea Stevenson',
  userAvatar: '/img/g5.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Kelsea Stevenson',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},
{
  userId: 'user007',
  userName: 'Ashley Mill',
  userAvatar: '/img/g6.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Ashley Mill',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},
{
  userId: 'user008',
  userName: 'Shelly Mooney',
  userAvatar: '/img/g7.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Shelly Mooney',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},
{
  userId: 'user009',
  userName: 'Andrew Almond',
  userAvatar: '/img/b1.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Andrew Almond',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},{
  userId: 'user010',
  userName: 'Alton Roberts',
  userAvatar: '/img/b2.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Alton Roberts',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},{
  userId: 'user011',
  userName: 'Danyal Myers',
  userAvatar: '/img/b3.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Danyal Myers',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},{
  userId: 'user012',
  userName: 'Payton Sellers',
  userAvatar: '/img/b4.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Payton Sellers',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},{
  userId: 'user013',
  userName: 'Logan Mellor',
  userAvatar: '/img/b5.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Logan Mellor',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},{
  userId: 'user014',
  userName: 'Jordi Franklin',
  userAvatar: '/img/b6.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Jordi Franklin',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},{
  userId: 'user015',
  userName: 'Jack Murphy',
  userAvatar: '/img/b7.jpg',
  userFriendStatus: '',
  userIntro:
    'My name is Jack Murphy',
  userCompany: '',
  userJobTitle: '',
  userEducation: '',
  userLocation: '',
  userInstagram: '',
  userRelationship: '',
  userFavAlbums: [
    {
      audioId: '132456gh',
      audioSrc: 'What_Is_Love',
      audioTitle: 'What Is Love',
      audioImage: 'album_What_Is_Love',
      album: 'What Is Love',
      artist: 'Melanie Ungar',
      audioType: '',
    },
  ],
},
];