import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { motion } from 'framer-motion';

import { toTopVariants } from '../src/common/AniVarients';

const About: NextPage = () => {
  return (
    <div className="cs-main-bg-theme">
      <Head>
        <title>SameVibes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.div
        className="no-scrollbar container mx-auto h-full overflow-y-auto pb-16 pt-16"
        initial="initial"
        animate="enter"
        exit="exit"
        variants={toTopVariants}
      >
        <div className="cs-block-style-white-theme dark:cs-block-style-grey-900 text-grey-900 my-4 mb-16 flex flex-col items-center pb-12 dark:text-white">
          <div className="relative my-4 h-32 w-32 2xl:h-40 2xl:w-40">
            <Image
              className="rounded-full"
              src="/img/me.jpg"
              alt="me"
              layout="fill"
              objectFit="cover"
            />
          </div>
          <div className="mt-2 text-center text-xl font-semibold">
            Mike Chen
          </div>
          <div className="px-4">
            <div className="mt-4 text-base lg:text-lg">
              Front-end developer | Photographer | Based in Taipei
            </div>
            <div className="mt-2 text-base lg:text-lg">
              Using React for 4 years, developing with Vue for 2 year.
            </div>
            <div className="mt-2 text-base lg:text-lg">
              Familiar with TypeScript, React hooks, Redux, pixi.js, Vue,
              Nuxt.js and Next.js.
            </div>
          </div>
          <div className="p-4 lg:w-2/3">
            <div className="mt-8 py-2 text-lg font-semibold lg:mt-16 lg:text-xl">
              Leadership
            </div>
            <div className="indent-8 lg:text-lg">
              I led a junior developer to build a sports games analysis forum
              with Vue / Nuxt.js from scratch. Planned and built canvas 2D
              animation game that worth millions TWD using React. Set company
              website SEO with colleagues and developed a few custom projects
              independently in the last 2.5 years.
            </div>
            <div className="mt-8 py-2 text-lg font-semibold lg:mt-16 lg:text-xl">
              Two Pillars of Javascript
            </div>
            <div className="indent-8 lg:text-lg">
              I’m lucky to have the experience of using functional programming
              (FP) to refactor the same project written in object-oriented
              programming (OOP) style.
            </div>
            <div className="mt-4 indent-8  lg:text-lg">
              Applied advanced javascript concepts such as composable and pure
              component features of FP to write a new library aiming to solve
              the problem caused by OOP style library, which is tightly coupled
              and became hard to maintain. The refactored version’s render speed
              was two times faster.{' '}
            </div>
            <div className="mt-8 py-2 text-lg font-semibold lg:mt-16 lg:text-xl">
              Performance
            </div>
            <div className="indent-8 lg:text-lg">
              Performance does matter to us due to the large number of users. I
              tested our site with Lighthouse, and applied methods such as using
              reselect to memoize state, useCallback to memoize functions, lazy
              load and code splitting to reduce the initial load time, and
              minimize image size for production.
            </div>{' '}
            <div className="mt-4 indent-8  lg:text-lg">
              We also chose to manipulate canvas and WebGL with pixi.js and GSAP
              library to create 2D animations. The benefits from using pixi.js
              instead of Unity are 2-3 times faster developing time and much
              smaller file size.
            </div>
            <div className="mt-8 py-2 text-lg font-semibold lg:mt-16 lg:text-xl">
              Coding style
            </div>
            <div className="indent-8 lg:text-lg">
              I applied the clean code principle and design pattern like facade
              and bridge pattern to make code more readable and organized. Also
              used Typescript to defined types and minimized errors.
            </div>{' '}
            <div className="mt-8 py-2 text-lg font-semibold lg:mt-16 lg:text-xl">
              Good Team Player
            </div>
            <div className="indent-8 lg:text-lg">
              Figma and Swagger are the tools we used to communicate with
              project managers, UX designers and other developers. As a good
              team player, I’m responsible for writing the detailed introduction
              document for the project by using markdown to help the new
              developer.
            </div>
            <div className="mt-8 py-2 text-lg font-semibold lg:mt-16 lg:text-xl">
              Side Project
            </div>
            <div className="indent-8 lg:text-lg">
              SameVibes.net is a social platform based on music taste, allowing
              people to make friends with their music preferences. Phase one
              utilizes the most frequently played music and the playlist
              selected by users to collect data, Phase two will integrate
              Spotify’s playlists api to run the analysis and recommend new
              friends.
            </div>
            <div className="mt-4 indent-8  lg:text-lg">
              The tech stack for front end is built with Next.js, Typescript,
              Tailwind and for backend is used with Node / Express and MongoDB
              as database.
            </div>
            <div className="mt-8 py-2 text-lg font-semibold lg:mt-16 lg:text-xl">
              Self-Improvement
            </div>
            <div className="indent-8 lg:text-lg">
              I enjoy learning new things, And having the self-learning habit
              after daily work, I managed Tailwind, Typescript, Node / Express,
              MongoDB and integration testing tool Cypress.
            </div>
            <div className="mt-4 indent-8 lg:text-lg">
              Before being a web developer, I was a professional photographer
              specializing in pre-wedding and travel photos for foreigners
              traveling in Taipei. I gained experience with picture composition,
              how to create a good layout, and demonstrated smooth communication
              skills with foreign clients.{' '}
            </div>
            <div className="mt-8 py-2 text-lg font-semibold lg:mt-16 lg:text-xl">
              Hobby
            </div>
            <div className="indent-8 lg:text-lg">
              Besides photography, I’m a coffee lover as well. Addict to ice
              drip and filtered coffee. My favorite coffee beans are from East
              Africa and Central America. Which filled with a smooth butter
              scent, quite fit in with my warm personality.
            </div>
          </div>
        </div>
      </motion.div>
    </div>
  );
};

export default About;
