import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { motion, useMotionValue, useTransform } from 'framer-motion';

import { zWaveVariants, toTopVariants } from '../src/common/AniVarients';

const Price: NextPage = () => {
  const x = useMotionValue(0);
  const y = useMotionValue(0);
  const rotateX = useTransform(y, [-100, 100], [50, -45]);
  const rotateY = useTransform(x, [-100, 100], [-40, 40]);

  return (
    <div className="cs-main-bg-theme fixed pb-12">
      <Head>
        <title>SameVibes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.div
        className="container mx-auto overflow-y-auto lg:overflow-y-hidden h-full no-scrollbar relative flex justify-center items-center"
        initial="initial"
        animate="enter"
        exit="exit"
        variants={toTopVariants}
      >
        <div className=" w-full lg:w-2/3 h-2/3 absolute">
          <Image
            className="rounded-xl opacity-90 dark:opacity-70"
            src={'/img/img-bokeh-2.jpg'}
            alt="bokeh"
            layout="fill"
            objectFit="cover"
          />
        </div>
        <div className="flex justify-center items-center">
          <div className="card-wrapper">
            <motion.div
              className="card-bg-style p-8 w-60 h-80 flex flex-col justify-center"
              style={{ x, y, rotateX, rotateY, z: 100 }}
              drag
              dragElastic={0.1}
              dragConstraints={{ top: 0, left: 0, right: 0, bottom: 0 }}
              whileTap={{ cursor: 'grabbing' }}
              initial="initial"
              animate="enter"
              exit="exit"
              variants={zWaveVariants}
            >
              <div className="flex items-center text-center text-3xl font-semibold cs-gradient-logo-style-dark">
                SameVibes
              </div>
              <div className="absolute bottom-8 z-0 flex items-center text-white">
                <motion.div
                  style={{ x, y, rotateX, rotateY, z: 9000 }}
                  drag
                  dragElastic={0.06}
                  dragConstraints={{ top: 0, left: 0, right: 0, bottom: 0 }}
                  whileTap={{ cursor: 'grabbing' }}
                >
                  $1000
                </motion.div>
                <div className="ml-16 cs-gradient-btn-dark px-4 py-2 rounded-lg z-0">
                  Buy
                </div>
              </div>
              <motion.div
                className="absolute top-[calc(50%_-_4rem)] left-[calc(50%_-_4rem)] w-32 h-32"
                style={{ x, y, rotateX, rotateY, z: 10000 }}
                drag
                dragElastic={0.08}
                dragConstraints={{ top: 0, left: 0, right: 0, bottom: 0 }}
                whileTap={{ cursor: 'grabbing' }}
              >
                <Image
                  className=""
                  src={'/img/img-vip-badge.png'}
                  alt="vip-badge"
                  layout="fill"
                  objectFit="cover"
                />
              </motion.div>
            </motion.div>
          </div>
        </div>
      </motion.div>
    </div>
  );
};

export default Price;
