import type { NextPage } from 'next';
import Head from 'next/head';
import { useDispatch, useSelector } from 'react-redux';
import { useEffect } from 'react';

import User from '../src/components/shared/User';
import { getCurUser } from '../store/actionCreators/userAction';
import { RootState } from '../store/reducers';

const Profile: NextPage = () => {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(getCurUser('user001'));
  }, []);

  const curUserProfile = useSelector(
    (state: RootState) => state.userReducer.curUser
  );
  return (
    <div className="cs-main-bg-theme">
      <Head>
        <title>SameVibes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <User
        userProfile={curUserProfile}
        isNotHome={true}
        isProfile={true}
      ></User>
    </div>
  );
};

export default Profile;
